#pragma once
 
#include <limits.h>

#define NNPARSER_MAX_NETWORK_INPUTS			(10)
#define NNPARSER_MAX_NETWORK_OUTPUTS        (18)
#define NNPARSER_OPERATOR_MAX_DIMENSIONS	(4)
#define NNPARSER_OPERATOR_MAX_SHAPE	        (6)
#define NNPARSER_OPERATOR_MAX_INPUTS		(7)
#define NNPARSER_OPERATOR_MAX_OUTPUTS		(7)
#define NNPARSER_MAX_PAD_DIM                (8)
#define MAX_NN_LAYER_NAME					(256)

enum E_NNPARSER_ERROR
{
	E_NNPARSER_ERROR_NETWORK_USER_FILE = INT_MIN,
	E_NNPARSER_ERROR_OPERATOR_MAX_INPUTS_REACHED,
	E_NNPARSER_ERROR_OPERATOR_MAX_OUTPUTS_REACHED,
	E_NNPARSER_ERROR_DIMENSIONS_MAX_LENGTH_REACHED,
	E_NNPARSER_ERROR_INSERT_EXISTING_NODE,
	E_NNPARSER_OK = 0
};

enum E_PADDING_MODE
{
	E_NNPARSER_PAD_MODE_DEFAULT
};

enum E_FUSED_ACTIVATION
{
	E_NNPARSER_FUSED_NONE
};